services:
  # Backend API Service
  - type: web
    name: expense-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://expense-tracker-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: expense-tracker-frontend
    buildCommand: cd frontend/expense-tracker && npm install && npm run build
    staticPublishPath: frontend/expense-tracker/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://expense-tracker-api.onrender.com

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    user: expense_user
